### ISSUE TITLE
Unshield can't open Command & Conquer: Generals files

### ISSUE THREAD

**Issue by janisozaur** [twogood/unshield#102]
Using retail C&C Generals and unshield f097b07 (current master), I tried extracting assets for use in https://github.com/TheAssemblyArmada/Thyme, but unshield complains:
`Failed to open Data1.cab as an InstallShield Cabinet File`

This is surely an InstallShield installer:
```
$ strings setup.exe | grep -ic installshield
39
```

The `Data1.cab` file identifies itself as:
```
00000000  4d 53 43 46 00 00 00 00  49 84 3c 0a 00 00 00 00  |MSCF....I.<.....|
```

Any idea what could be the problem?

**Comment by twogood** [comment]
Please use https://www.cabextract.org.uk/ for files with MSCF signature

**Comment by janisozaur** [comment]
Right, it was pointed out to me even `file-roller` supports them. Can you maybe add a check for unwise users they should try with a more generic tool?

**Comment by twogood** [comment]
There is code for that:
```
  if (MSCF_SIGNATURE == common->signature)
      unshield_warning("Found Microsoft Cabinet header. Use cabextract (https://www.cabextract.org.uk/) to unpack this file."
```
I don't know why it didn't trigger for you though.
