### ISSUE TITLE
Always builds a static library

### ISSUE THREAD

**Issue by r-a-sattarov** [twogood/unshield#108]
Always builds a static library regardless of value of BUILD_STATIC option (`Linking C static library liblibunshield.a`).
On version 1.4.3 (October 2018) this does not happen, a dynamic library is created by default.

Сmake version 3.15.4

**Comment by twogood** [comment]
Thanks for the issue report! PR is welcome :)

**Comment by r-a-sattarov** [comment]
This error appeared after this commit
- https://github.com/twogood/unshield/commit/67c22aee9eeb479686b6b1e32131a85fd3dab31f#diff-4803677bd280f4dded52c428e3c8ac6c618508dcabcbe880b68be85897c2ad41

This code in `unshield\lib\CMakeLists.txt` will fixit this error:

`if(BUILD_STATIC)`
    `add_library(${PROJECT_NAME} STATIC ${LIBUNSHIELD_HEADES} ${LIBUNSHIELD_SOURCES})`
`else()`
    `add_library(${PROJECT_NAME} SHARED ${LIBUNSHIELD_HEADES} ${LIBUNSHIELD_SOURCES})`
`endif()`

**Comment by twogood** [comment]
Great job, thank you @r-a-sattarov!
