### ISSUE TITLE
Files identified as InstallShield .cabs but not accessible with unshield

### ISSUE THREAD

**Issue by AdamWill** [twogood/unshield#13]
I contacted David directly about a couple of files I found that were identified as InstallShield cabs, but which unshield couldn't open. He asked me to file an issue, so here it is.

Download the .exe from http://www.dell.com/support/drivers/us/en/04/DriverDetails/Product/dell-venue-8-pro?driverId=4F5N3&osCode=WB32A&fileId=3298803898&languageCode=en&categoryId=NI , extract it (it's a typical self-extracting .exe) and see the files data1.cab and data2.cab . They're pretty clearly InstallShield files, but unshield doesn't open them.

**Comment by twogood** [comment]
@AdamWill Could you please provide an updated URL to this download?

**Comment by AdamWill** [comment]
Um. Honestly? No. I don't remember which driver this was. Probably one of the ones at http://www.dell.com/support/home/ca/en/cabsdt1/product-support/product/dell-venue-8-pro/drivers .

**Comment by szepeviktor** [comment]
@twogood Could it be that I am in the same situation?
http://www1.canyon.eu/files/downloads/drivers/cne-cwc1.zip
```
unshield x ~/tmp/data1.cab
Failed to open /root/tmp/data1.cab as an InstallShield Cabinet File
```
Thanks.

**Comment by twogood** [comment]
@szepeviktor What version of unshield? If I run the .exe in Window and grab the data1.cab from wine's temporary directory I can extract most files with the latest unshield, but some files claim to be in data2.cab, which does not seem to be extracted before the installation fails.

**Comment by szepeviktor** [comment]
Thank you!

I ran it on linux as I am not able to compile anything on Windows and there's no exe in the releases: https://github.com/twogood/unshield/releases
Am I wrong?

**Comment by szepeviktor** [comment]
Oh! From the TEMP! I see.
I've use IsXunpack.exe to get both cabs.

**Comment by twogood** [comment]
Yes, I meant the .exe in your zip ;-)

**Comment by szepeviktor** [comment]
So I have data1 + data2.cab:
```
~/tmp/unshield-master/binary/unshield x data1.cab
Failed to open data1.cab as an InstallShield Cabinet File
```

**Comment by twogood** [comment]
PS. I'll gladly include a MIT licensed version of IsXunpack in unshield.

**Comment by szepeviktor** [comment]
OK but the resulting cab files only open with InstallShield's `IsCabView.exe`
not with unshield.

**Comment by twogood** [comment]
Can you provide the cab files?

**Comment by szepeviktor** [comment]
https://www.wetransfer.com/downloads/ae2d233b5638150376f5f777c02f5e1520170216201937/87be9c102a609bceef4fdcc7e0574d9c20170216201937/279419

**Comment by twogood** [comment]
@szepeviktor You need data1.hdr too for unshield to work.

**Comment by szepeviktor** [comment]
[data1-hdr.zip](https://github.com/twogood/unshield/files/781483/data1-hdr.zip)

**Comment by twogood** [comment]
You need it more than I do,  put it next to the cab files and unshield works fine.

**Comment by szepeviktor** [comment]
Thank you.
You are very kind.

**Comment by twogood** [comment]
You're welcome, @szepeviktor ! :-)

**Comment by goncalveses** [comment]
Hello, I am not able to extract the files from my data.cab could anyone help me?

**Comment by twogood** [comment]
@goncalveses Please create a separate issue and add links to your data*cab and data*hdr files.

**Comment by tafamas** [comment]
Hello guys I have the same problem with one of my installshield cab files

**Comment by lvbakker** [comment]
> @szepeviktor You need data1.hdr too for unshield to work.

Thank you! i was having the same issues but didn't know i needed the .hdr file.
