### ISSUE TITLE
warning: remote HEAD refers to nonexistent ref, unable to checkout

### ISSUE THREAD

**Issue by iguanatamer** [twogood/unshield#133]
When trying to install from the AUR I get this error when pulling the git repo.

```
Cloning into 'unshield'...
done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```

**Comment by twogood** [comment]
I don't know what an AUR is but I have renamed the `master` branch to `main`. Could it be the reason?

I thought GitHub did setup a redirect though?

**Comment by twogood** [comment]
Oh, AUR=Arch User Repository

**Comment by kratz00** [comment]
@iguanatamer Are you talking about https://aur.archlinux.org/packages/unshield-git
If so, the last update was in 2017, this was before the branch was renamed.
To me the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=unshield-git) needs to be fixed and it is not an upstream issue.

Why not use the official package - https://archlinux.org/packages/community/x86_64/unshield/
It supports the last officially released unshield version.

**Comment by twogood** [comment]
Thanks @kratz00 !
