### ISSUE TITLE
travis-ci.org is ceased

### ISSUE THREAD

**Issue by kratz00** [twogood/unshield#138]
See https://travis-ci.org/github/twogood/unshield:

`Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. `

See https://docs.travis-ci.com/user/migrate/open-source-repository-migration for an overview on how to migrate to travis-ci.com

**Comment by twogood** [comment]
Yeah I know... I'd like to use GitHub actions instead.

**Comment by kratz00** [comment]
How do you feel about the AppVeyor integration?
The configuration in the main branch looks differently from what is actually executed in a pull request and on the other hand it is failing.

It seems it could also be replaced by GitHub actions (https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job).

Instead of having three different CI pipelines, GitHub actions could be the one and only (From my naive standpoint I could not find something which is not supported in comparison to the other two).

**Comment by twogood** [comment]
@kratz00 I pretty much hate AppVeyor, so Windows builds should definitely also run on GitHub Actions.

**Comment by kratz00** [comment]
Fixed by https://github.com/twogood/unshield/commit/71c96a21c31a87e9ede5008cdf5dbc460792ecb7
