### ISSUE TITLE
Commented out for a long time

### ISSUE THREAD

**Issue by polluks** [twogood/unshield#151]
https://github.com/twogood/unshield/blob/4852238d1d9aa736b48f0e7405c19ca6a0996b35/src/unshield.c#L223
this seems to be unintended IMHO

**Comment by twogood** [comment]
Yeah, because they are implemented as command line options but setting them does not have any effect when the application runs... so they could be removed or implemented :)

**Comment by polluks** [comment]
I see, so the manual is not up-to-date.
