### ISSUE TITLE
Question on supported installer types

### ISSUE THREAD

**Issue by greenozon** [twogood/unshield#184]
I"m having the .exe installer with big size (> 1 GB)
but thats defintely an InstallShield one
does this tool support extracting intenral files from withiin the .exe installer?
or it supports only IS cab files

**Comment by twogood** [comment]
Start the .exe with Wine or on a Windows machine to let it extract the .hdr
and .cab files to a temporary directory and copy them from there for use by
unshield.

\David

.NET and Flutter expert
+46 768 832493

**Comment by greenozon** [comment]
yeah, good points, thanks
so the grand .exe extracs a couple of folders into TEMP dir
and the biggest installer is still .msi
no any .hdr or .cab around

but I got your idea - I need to get .hdr  or .cab in order to start using this tool

**Comment by twogood** [comment]
The most recent versions of InstallShield probably just uses .msi, and
unshield can't help with that...

\David

.NET and Flutter expert
+46 768 832493
