### ISSUE TITLE
installshield cab version 17 and later list/extract filename only 1 character

### ISSUE THREAD

**Issue by ddgg** [twogood/unshield#19]
I have some stock invester pro installshield exe, use exiftool I can see that they are created using various versions of installshield , before version 12 unshield work perfectly, but after version 17 till 19, unshield list file in a strange way, only one character for each part in the path/filename, 
[Imgur](http://i.imgur.com/YKJR0pQ.jpg)

any known issues for this? thanks

**Comment by twogood** [comment]
I need some example files to work with to solve this.

Thanks!

**Comment by ddgg** [comment]
hi, this is a self extractable install exe

https://github.com/ddgg/stockinvestorpro/raw/master/1.exe

thank you for the great software

**Comment by twogood** [comment]
The file names show correctly now, but unfortunately only a very limited number of files were successfully extracted :-(

**Comment by ddgg** [comment]
@twogood , thank you for the update, it's working now for the version 18/19 exes, but today I tried another exe(version 17), the single character problem persists, would you please have a look at it? thanks

[v17 exe](https://github.com/ddgg/stockinvestorpro/commits/master/v17.exe)

**Comment by twogood** [comment]
OK, handling file names in version 17 just like 18/19 now. Please give it a try.

**Comment by ddgg** [comment]
works great now, thanks

**Comment by twogood** [comment]
:+1:
