### ISSUE TITLE
Fails to build when building inside of jail using cmake

### ISSUE THREAD

**Issue by h3xx** [twogood/unshield#22]
The file `unshield_config.h` isn't made available to source files when building in a build jail.

Steps to reproduce:

    git clone git://github.com/twogood/unshield.git
    cd unshield
    mkdir -p __build_jail__
    cd __build_jail__
    cmake ..
    make

Error message:

    Scanning dependencies of target convert_utf
    [  9%] Building C object lib/convert_utf/CMakeFiles/convert_utf.dir/ConvertUTF.c.o
    Linking C static library libconvert_utf.a
    [  9%] Built target convert_utf
    Scanning dependencies of target libunshield
    [ 18%] Building C object lib/CMakeFiles/libunshield.dir/bswap.c.o
    In file included from /tmp/git/unshield/lib/bswap.c:2:0:
    /tmp/git/unshield/lib/internal.h:6:29: fatal error: unshield_config.h: No such file or directory
     #include "unshield_config.h"
                                 ^
    compilation terminated.
    make[2]: *** [lib/CMakeFiles/libunshield.dir/bswap.c.o] Error 1
    make[1]: *** [lib/CMakeFiles/libunshield.dir/all] Error 2
    make: *** [all] Error 2

**Comment by twogood** [comment]
@stopiccot: do you have any suggestions?

**Comment by h3xx** [comment]
I have solved it, but I'm not certain it's the "right" way to solve it.

unshield_config.h is generated as a result of running cmake, right? Generated files *should* go under `${CMAKE_CURRENT_BINARY_DIR}` but the source files look for it in the source dirs.

**Comment by twogood** [comment]
Yes, it is generated from unshield_config.h.in at build time.

**Comment by h3xx** [comment]
I actually think I fixed it the "correct" way with my pull request. Should be backward-compatible with those who prefer to build the source code in-tree.

**Comment by twogood** [comment]
Thank you very much!
