### ISSUE TITLE
can't decompress 3 files from "The Feeble Files - spanish version" old archive

### ISSUE THREAD

**Issue by a-detiste** [twogood/unshield#27]
Hi,

unshield can't decompress 3 files from `data1.cab` provided by  the Spanish version
of "the Feeble Files" (Charisma.smk, Qtime.smk & Run95.exe)

Without the `-O` flag, this archive can't be uncompressed at all.

Log for one of the 3 files:

`unshield -D 3 -O x data1.cab Charisma.smk > charisma.txt 2>&1`
http://ssh.detiste.be/charisma.txt

Whole CD1:
https://drive.google.com/file/d/0B6x6rDZxk-NbUkZaT28waXlaMWs/view

The (only ?) usefull inner archive:
http://ssh.detiste.be/data1.cab  (26M)

Greets,

**Comment by twogood** [comment]
Isn't there a second CD-ROM containing a data2.cab file?

**Comment by twogood** [comment]
I can't really explain why these files fail. The Charisma.smk and Run95.exe files are probably just missing some null padding at the end, but Qtime.smk is worse off. It should expand to 11 970 484 bytes but stops at 8 732 560 bytes with "data error" from zlib's ``inflate()`` function...

**Comment by a-detiste** [comment]
Aim of out [project](http://pkg-games.alioth.debian.org/game-data/) is to be able to install all these old commercial games without requiring Wine or even a x86 cpu. For now telling people to install to /tmp & repack from there is just fine as a workaround.

`Unshield` works perfectly for the Jedi Academy & the Arx Fatalis japanase Demo :smile: 

For InstallWise (needed by Return To Caste Wolfenstein), I found some dubious licensed pascal source codes with comment & variable names in german that compiled for win95 ... let's say I'll have a look at that "_later_". In the end it's about the same thing: calling `inflate()` with the right data...

**Comment by twogood** [comment]
The game-data-package project looks like an excellent initiative! It also seems to be an excellent test bed for unshield! :-)

I just pushed a couple of improvements to master. Enjoy!

**Comment by twogood** [comment]
Slightly off-topic: I have some really old code (MIT license) to also extract files from DllInflate, Inno Setup, InstallShield SFX, Installer VISE, Nullsoft Installer, SetupFactory 5/6, and maybe something else. See http://sourceforge.net/p/synce/code/HEAD/tree/trunk/orange/lib/

**Comment by a-detiste** [comment]
Great !

```
git pull ; make
./src/unshield -d /tmp -O x ../../gdp/feeble-files/es/Feeble\ CD1/data1.cab
```
didn't emitted any warning, will verify the md5 later.

When you'll publish a new release, I'll ask the Debian maitainer to update the package,
it's a bit lacking behind: https://packages.qa.debian.org/u/unshield.html

**Comment by a-detiste** [comment]
> Slightly off-topic

I always first try what is already packaged in Debian, like `7z` or `InnoExtract`.

I think 7z handles NullSoft.

InnoExtract is well maitained with an active community (my Pull Request got in :smile: ),
so I'd prefer that; it's also usable in the `Jessie` release.

It's not that I'm lazy, but we want to keep this project back-portable to stable,
without having to backport tens of C/C++ depedencies with versioned libs.

I gave backports a try [there](https://launchpad.net/~alexandre-detiste/+archive/ubuntu/ppa/+packages), but as I never used Ubuntu myself, and the one friend I did this for hasn't acked yet; it's not yet tested ... well I once installed the game-data-packager-all.deb on a RaspberyyPi, because Inkscape was segfaulting on this day because of a library mismatch.

> http://sourceforge.net/p/synce/code/HEAD/tree/trunk/orange/lib/

I do remember to have tested that once without succes for my archive, then I spent time locating a smaller InstallWise archive; I somehowe remembered those old ICQ installers that could be a smaller testbed (funny I remember that but can't remember my colleages names) ... then I postponed it.

By all means I'd prefer having a fixable MIT codebase that a working windows executable.

Orange was removed from the archive back then, but I could bring it back if it was needed for a precise game and not simply "it may be usefull for someone":
https://packages.qa.debian.org/o/orange.html

Other bits of code:
https://github.com/lmop/exwise

-----

http://kannegieser.net/veit/programm/index_e.htm

http://kannegieser.net/veit/quelle/e_wise_src.arj

I first thought this was not "Debian Free Software Guidelines"-compliant, but it's just an BSD-style attribution clause; I guess that's not much to pay back to have a working InstallWise unpacker.

```
{
   Copyright (c) 1995 by Oliver Fromme  --  All Rights Reserved

   Address:  Oliver Fromme, Leibnizstr. 18-61, 38678 Clausthal, Germany
   Internet:  fromme@rz.tu-clausthal.de
   WWW:  http://www.tu-clausthal.de/~inof/

   Freely distributable, freely usable.
   The original copyright notice may not be modified or omitted.
}
```

**Comment by twogood** [comment]
I'll publish a new release after merging a patch for #28

Orange is not maintained enough be in Debian, but new projects could be built upon that code. Not by me, though.

**Comment by a-detiste** [comment]
I'd prefer too to have an easy to maintian single-format unarchiver, not something with layers of format abstractions I don't personally need. I'll handle this someday.

**Comment by a-detiste** [comment]
> The game-data-package project looks like an excellent initiative!

And a lot of fun too.
