### ISSUE TITLE
unshield cannot deal with non-utf filename

### ISSUE THREAD

**Issue by maz-1** [twogood/unshield#28]
I am trying to extract files from this file
http://tkool.jp/assets/files/2003rtp.zip

command I use :

  unar -encoding SHIFT-JIS 2003rtp.zip
  cd "2003RTPｾｯﾄｱｯﾌﾟ"
  unar RPG2003RTP.exe
  cd RPG2003RTP
  unshield x data1.cab

However, unshield cannot set the original character encoding like unarchiver, all non-ascii characters are converted to underline (In this case these characters are encoded in shift-jis).
 Any way to solve the problem?

**Comment by twogood** [comment]
Thank you for your issue report! The internationalization of unshield is obviously lacking. Can you please try to modify the source code like this and see if it gives you correct filenames?

```diff
diff --git a/src/unshield.c b/src/unshield.c
index 158195f..5bfedaa 100644
--- a/src/unshield.c
+++ b/src/unshield.c
@@ -329,7 +329,7 @@ static bool extract_file(Unshield* unshield, const char* prefix, int index)
         break;
 
       default:
-        if (!isprint(*p))
+        if (0 && !isprint(*p))
           *p = '_';
         else if (make_lowercase)
           *p = tolower(*p);
@@ -349,7 +349,7 @@ static bool extract_file(Unshield* unshield, const char* prefix, int index)
 
   for (p = filename + strlen(dirname); *p != '\0'; p++)
   {
-    if (!isprint(*p))
+    if (0 && !isprint(*p))
       *p = '_';
     else if (make_lowercase)
       *p = tolower(*p);

```

**Comment by maz-1** [comment]
Works! Although filenames are in a mess, but they are no longer converted to underline ,so I can fix them with convmv. For me that's enough.

**Comment by twogood** [comment]
OK! File names are supposed to be in UTF-8, but maybe they are not :-)

**Comment by maz-1** [comment]
What do you think of this?
https://github.com/maz-1/unshield/commit/5c7f68954df58c94892482962e85b5e2f99d8c08

**Comment by twogood** [comment]
Looks good, send a pull request!
