### ISSUE TITLE
Issues Building with MinGW (64-bit)

### ISSUE THREAD

**Issue by 6XGate** [twogood/unshield#33]
I has issues compiling unshield under MinGW, the 64-bit version.  I have attached the following patch of changes I had to do to make it build.  It also allows overriding the use of OpenSSL with the internal MD5 code, even when OpenSSL is found.

[unshield.patch.txt](https://github.com/twogood/unshield/files/116091/unshield.patch.txt)

**Comment by twogood** [comment]
Thanks! Unfortunately adding libiconv to target_link_libraries breaks the build on my Linux machine, as iconv is included in libc. Is this an easy fix for you? Thanks again!

**Comment by 6XGate** [comment]
Should be, just make the POSIX systems and Windows systems link differently.

**Comment by 6XGate** [comment]
Okay, I changed the libiconv linkage so only happens on Windows (MinGW or MSYS).  Also added fixes to allow MSYS compilation as well.

[unshield.patch.txt](https://github.com/twogood/unshield/files/116514/unshield.patch.txt)

**Comment by twogood** [comment]
Much better! But the message USE_OUR_OWN_MD5 comes twice, is that deliberate? Also I realized #36 right now.

**Comment by 6XGate** [comment]
Let me check, they may have been a debugging message that left behind

**Comment by 6XGate** [comment]
Any other issues noticed with the patch?

**Comment by twogood** [comment]
No, just late with merging.

tors 11 feb. 2016 22:51 Matthew Holder <notifications@github.com> skrev:

**Comment by 6XGate** [comment]
any thoughts on getting this merged in?

**Comment by twogood** [comment]
Sorry, I will take a look at this again!

**Comment by twogood** [comment]
I'm having a really hard time getting #57 to build on the old Ubuntu Travis is running on. @6XGate would you be able to setup a build on https://www.appveyor.com/ for Unshield?

**Comment by 6XGate** [comment]
I'll need to finish that soon.
