### ISSUE TITLE
Unable to List or Extract Files from Some InstallShield 15 Cabinets

### ISSUE THREAD

**Issue by 6XGate** [twogood/unshield#34]
I have tried using _unshield_ on the following cabinet set from InstallShield 15 installers with no luck.

[sp71906.zip](https://github.com/twogood/unshield/files/116196/sp71906.zip)

**Comment by twogood** [comment]
Works fine for me on Linux. Could you please provide some output from unshield?

**Comment by 6XGate** [comment]
Here is the `-D 3` output from unshield.
   > ..\unshield.exe -D 3 l data1.cab
   [unshield_read_headers:226] Reading header from .hdr file 1.
   [unshield_read_headers:262] Failed to read from header file 1. Expected = 82137, read = 1364
   [unshield_open_force_version:363] Failed to read header files
   Failed to open data1.cab as an InstallShield Cabinet File

**Comment by twogood** [comment]
Thanks! Could you please try to edit the ``fopen()`` call  around line 72 in ``helper.c`` and change ``"r"`` to ``"rb"``, recompile and see if unshield works better?

**Comment by 6XGate** [comment]
sure

**Comment by twogood** [comment]
Great!
