### ISSUE TITLE
Using our own MD5 even if we have OpenSSL?!

### ISSUE THREAD

**Issue by twogood** [twogood/unshield#36]
```
$ ./rebuild.sh 
+ export CFLAGS=-Wall -Werror -ggdb3
+ cmake -DCMAKE_INSTALL_PREFIX:PATH=/var/tmp/unshield .
-- OPENSSL_FOUND: TRUE
-- USE_OUR_OWN_MD5: ON
-- BUILD_STATIC: OFF
-- Configuring done
```

If we have OpenSSL, **don't** use our own MD5 code.

**Comment by stopiccot** [comment]
KInda weird cause there is a check for it already https://github.com/twogood/unshield/blob/master/CMakeLists.txt#L49

**Comment by twogood** [comment]
Exactly. And I have lots of other things to do so I hope that one day maybe some CMake guru will figure it out... :-)

With #33 it says:
```
-- USE_OUR_OWN_MD5: ON
-- OPENSSL_FOUND: TRUE
-- USE_OUR_OWN_MD5: ON
-- BUILD_STATIC: OFF
```

**Comment by stopiccot** [comment]
Please post some system info your are running to get this kind of output

**Comment by stopiccot** [comment]
Also you can "debug" cmake scripts using `message()` function

**Comment by 6XGate** [comment]
#33 should only do that when you add `-dUSE_OUR_OWN_MD5=ON` to the command-line.  That `rebuild.cmd` for Windows should be the only thing to do that.

**Comment by 6XGate** [comment]
Okay, under _MSYS_, when it finds _OpenSSL_ it does turn off the `USE_OUR_OWN_MD5` setting. Maybe this is specific to Linux?

**Comment by twogood** [comment]
It looks like this may be a caching issue of sorts at my side.

**Comment by 6XGate** [comment]
any thoughts on getting this merged in?

**Comment by twogood** [comment]
Hi,

Do you mean a fix for https://github.com/twogood/unshield/issues/36 ?


Best regards,

\David


tors 23 juni 2016 kl 22:57 skrev Matthew Holder <notifications@github.com>:

**Comment by 6XGate** [comment]
From your response, I thought this was just a caching issue when using my patch from #33.
