### ISSUE TITLE
Windows/MinGW; Unable to Read Cabinet From Path With Numbers

### ISSUE THREAD

**Issue by 6XGate** [twogood/unshield#37]
I'm having an issue with ready cabinets when a path I give unshield contains numbers.  I image this may take few changes to fix, and the workaround is just to be in the folder where the cabinet is, but I figured I should make you aware of the issue.

    unshield -D 3 l sp71906\data1.cab
    [unshield_fopen_for_reading:60] File sp1.hdr not found even case insensitive

    [unshield_read_headers:232] Could not open .hdr file 1. Reading header from .cab file 1 instead.
    [unshield_fopen_for_reading:60] File sp1.cab not found even case insensitive

    [unshield_open_force_version:363] Failed to read header files
    Failed to open sp71906\data1.cab as an InstallShield Cabinet File

**Comment by twogood** [comment]
Nice catch! I need to check if the same issue exists on Linux.

**Comment by twogood** [comment]
Works fine on Linux. The problem is using `\` as a path separator. It should work fine on Windows/MinGW if you use `/` as path separator, e.g. `unshield -D 3 l sp71906/data1.cab`. Can you confirm?

**Comment by 6XGate** [comment]
I'll check that out

**Comment by 6XGate** [comment]
Yeap, switching it to forward slashes (/) did indeed fix the issue.

**Comment by twogood** [comment]
Thanks! That'll work for now! :-)
