### ISSUE TITLE
Gentoo ebuilds - minor cmake path issue

### ISSUE THREAD

**Issue by bobwya** [twogood/unshield#38]
Hi,
I was just adding the unshield package to my Overlay - since the in-tree (Gentoo) ebuilds are very out-dated.

I'm still carrying this small patch for the live (git) ebuild:
```diff -u1 -rN a/CMakeLists.txt b/CMakeLists.txt
--- a/CMakeLists.txt    2016-02-24 08:35:02.521305407 +0000
+++ b/CMakeLists.txt    2016-02-24 08:48:59.499423674 +0000
@@ -62,2 +62,3 @@
 include_directories(${CMAKE_CURRENT_BINARY_DIR})
+include_directories(${CMAKE_CURRENT_BINARY_DIR}/lib)```

It would be nice if I wasn't :-)

**Comment by twogood** [comment]
Thanks, but could you explain the scenario where this is needed? Is it when building outside of the source directory? I took a look at this now and with my limited CMake knowledge I would suggest this patch, reversing the `#include` changes by @h3xx :

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1cf573b..3983a34 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -59,7 +59,6 @@ message(STATUS "BUILD_STATIC: ${BUILD_STATIC}")
 add_definitions(-DHAVE_CONFIG_H)
 configure_file(${CMAKE_CURRENT_SOURCE_DIR}/lib/unshield_config.h.in ${CMAKE_CURRENT_BINARY_DIR}/lib/unshield_config.h)
 configure_file(${CMAKE_CURRENT_SOURCE_DIR}/libunshield.pc.in ${CMAKE_CURRENT_BINARY_DIR}/libunshield.pc @ONLY)
-include_directories(${CMAKE_CURRENT_BINARY_DIR})
 
 # To force position independent code for static libs on Linux x64
 if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
diff --git a/lib/internal.h b/lib/internal.h
index 1f5718a..0ea88be 100644
--- a/lib/internal.h
+++ b/lib/internal.h
@@ -3,7 +3,7 @@
 #define __internal_h__
 
 #include "libunshield.h"
-#include "lib/unshield_config.h"
+#include "unshield_config.h"
 
 #if HAVE_STDINT_H
 #include <stdint.h>
diff --git a/src/unshield.c b/src/unshield.c
index d8336bd..ed2b0db 100644
--- a/src/unshield.c
+++ b/src/unshield.c
@@ -13,7 +13,7 @@
 #include <unistd.h>
 #include "../lib/libunshield.h"
 #ifdef HAVE_CONFIG_H
-#include "lib/unshield_config.h"
+#include "../lib/unshield_config.h"
 #endif
 #if HAVE_FNMATCH
 #include <fnmatch.h>
```

**Comment by bobwya** [comment]
I can see straight away that won't :-) In fact it would make things a lot worse... Oh my dear lord...

[Gentoo](https://en.wikipedia.org/wiki/Gentoo_Linux), uses Portage which is an advanced, source-based package manager. Loosely it's based of the FreeBSD Ports System. Multiple package builds can run in parallel - each is built in a chroot sandbox.

To illustrate - the "meat and potatoes" from the live (git) **unshield** ebuild script I've cobbled together:
```
src_prepare() {
        epatch "${FILESDIR}"/${P}-fix_cmake_include_paths.patch
        cmake-utils_src_prepare
}

src_configure() {
        local mycmakeargs=(
                --with-ssl
                $(cmake-utils_use_with static-libs static) \
        )
        cmake-utils_src_configure
}
```

So everything is automated.

Clones the git repository to:
``` /tmp/portage/app-arch/unshield-9999/work/unshield-9999 ```
=**CMAKE_CURRENT_SOURCE_DIR**

Creates a build dir:
 ``` /tmp/portage/app-arch/unshield-9999/work/unshield-9999_build ```
=**CMAKE_CURRENT_BINARY_DIR**

So it's effectively running:
```
cd /tmp/portage/app-arch/unshield-9999/work/
mkdir -p unshield-9999_build
cd unshield-9999_build
cmake ../unshield-9999
make
```

This is common practice - i.e. to use a completely separate **cmake** **build** directory.
Your software does not build in this scenario. Since this part of your cmake script:
``` configure_file(${CMAKE_CURRENT_SOURCE_DIR}/lib/unshield_config.h.in ${CMAKE_CURRENT_BINARY_DIR}/lib/unshield_config.h) ```
creates a library in **${CMAKE_CURRENT_BINARY_DIR}/lib** - this subdirectory is then not in the path when running **make**.

It would be nice if other people didn't come across this issue... So I was just trying Upstream my patch. It fixes the broken lib path **make** issue I described... _qed_.

**Comment by twogood** [comment]
OK, thanks again! I can't reproduce the issue myself though, not even when I used a separate cmake build directory.

**Comment by a-detiste** [comment]
@bobwya

Dear CMake expert :smile: 

There was a patch in Debian package for v1.0 againt autoconf script to disable RPath.
Now I'll need a new patch to disable RPath in new CMake build.

But maybe this could just be removed altogheter upstream.

(Hey, it's not that I'm lazy, but if nobody needs that; then it's just superfluous fluff,
"less is more")

https://wiki.debian.org/RpathIssue

```
You can stop cmake adding the flags for rpath-setting by adding

       SKIP_BUILD_RPATH TRUE

to the properties on the relevant binary in CMakeLists.txt e.g.

set_target_properties(foolib PROPERTIES SKIP_BUILD_RPATH TRUE)


----> Ideally this change would be upstreamed.
```

**Comment by twogood** [comment]
@a-detiste : Maybe I should skip RPath by default?

**Comment by bobwya** [comment]
Hah, hah. That made me laugh: "_Dear CMake expert_".
Folks should take any comments I make about cmake issues with a pince of salt... :-)

However the **RPATH** issue is almost totally unrelated to this issue... I'm simply talking about **make** being unable to locate a C header file at **build** time. The **RPATH** stuff is dynamic linking issues - when putting your "binary / libraries" into production (i.e. **runtime** issues).

Funny I've just been raising some linker inconsistencies in Gentoo recently...

**Comment by a-detiste** [comment]
I do know that it was unrelated, but 1) maybe you knew a bit more 2) you're interrested in unshield.

Now, I stumbled on: https://github.com/twogood/unshield/commit/e0d764f73424392d12eb0234c693f69fef2bc2f1

Which links to https://cmake.org/Wiki/CMake_RPATH_handling
which helps me comming up with this patch.

This way we have _both_ wanted behaviour: unshield manually built in /home 
will hapilly run from the git tree and distribution-built unshield will only
loads .so from /usr/lib !

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 2129ed0..d4e0ea9 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -1,4 +1,7 @@
+LIST(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
+IF("${isSystemDir}" STREQUAL "-1")
 SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}")
+ENDIF("${isSystemDir}" STREQUAL "-1")
```

The different memory mapping create a lot of noise, only the line about libunshield.so.1.3
is relevant (I have /usr/lib/x86_64-linux-gnu/libunshield.so.0.0.0 from v1.0)

```
diff -u <(ldd debian/tmp/usr/bin/unshield) <(ldd obj-x86_64-linux-gnu/src/unshield)
--- /dev/fd/63  2016-02-24 21:59:37.809844678 +0100
+++ /dev/fd/62  2016-02-24 21:59:37.813844598 +0100
@@ -1,8 +1,8 @@
-       linux-vdso.so.1 (0x00007ffd2017c000)
-       libunshield.so.1.3 => not found
-       libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f016a67a000)
-       libssl.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 (0x00007f016a40a000)
-       libcrypto.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007f0169fa2000)
-       libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0169bfa000)
-       libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f01699f2000)
-       /lib64/ld-linux-x86-64.so.2 (0x000055861cf50000)
+       linux-vdso.so.1 (0x00007ffd5917c000)
+       libunshield.so.1.3 => /home/tchet/git/unshield-upstream/obj-x86_64-linux-gnu/lib/libunshield.so.1.3 (0x00007f4b716f2000)
+       libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4b7149a000)
+       libssl.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 (0x00007f4b7122a000)
+       libcrypto.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007f4b70dc2000)
+       libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b70a1a000)
+       libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4b70812000)
+       /lib64/ld-linux-x86-64.so.2 (0x000055ad588bd000)
```

**Comment by twogood** [comment]
Sounds good. Created #40 for further discussion.
