### ISSUE TITLE
Fix RPath

### ISSUE THREAD

**Issue by twogood** [twogood/unshield#40]
Follow up on #38

**Comment by twogood** [comment]
@stopiccot Could you please have a look at the RPath discussion at the end of #38 and give some input?

**Comment by evgeni** [comment]
Why closing this? I still think that we should not set rpath.

**Comment by twogood** [comment]
Sorry, I must have mixed up this with something else :-)

**Comment by twogood** [comment]
PR is welcome :-)

**Comment by evgeni** [comment]
I think the patch by @a-detiste in #38 looks good?

**Comment by a-detiste** [comment]
Hi,
I had completely forgotten about this, but with a fresh mind it sill seems the right thing to do.

**Comment by twogood** [comment]
Thank you @a-detiste !
