### ISSUE TITLE
Extraction goes into infinite loop with some cab files

### ISSUE THREAD

**Issue by okuuva** [twogood/unshield#45]
When trying to extract cab files from [Texas Instruments Avigo Manager](https://www.ti.com/organizers/avigo/docs/amupdate.html), extraction goes into infinite loop.

`unshield -D3 x data5.cab` results in this:
http://pastie.org/pastes/10830939/text?key=9gocgtm2mhruuhy0ngiq

Same thing for all the cab files in the zip.

Here is a direct link to the file in question: https://www.ti.com/organizers/avigo/docs/avigomanager11b22.zip

**Comment by twogood** [comment]
Thanks for the bug report. That's really interesting! I'll see if I can find anything obvious.

As always, PR is welcome! :-)

**Comment by twogood** [comment]
That was some really old InstallShield files you had there... Fixed in git now, thanks again! And you need to use the `-O` command line option to enable "old (de)compression".

**Comment by okuuva** [comment]
Yes, seems to be working after a pull and a rebuild. Thank you so much for such a fast response and fix!
