### ISSUE TITLE
lib/convert_utf/ConvertUTF seems non-free

### ISSUE THREAD

**Issue by evgeni** [twogood/unshield#60]
Hey,

it seems that the code we embed in lib/convert_utf/ConvertUTF.c is not really free software.

Here is an explanation of the issue in ghostscript:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823100
https://bugs.ghostscript.com/show_bug.cgi?id=697121

the fix for ghostscript is here:
http://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=273a133110838ee5702e7eb6409a853c598211b2
http://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=727aeab76c39026722e3e492a30ae2f7c218c1ec

**Comment by twogood** [comment]
Oups, my bad. Good thing there are more eyes looking for these kind of things. I guess I can't take the ghostscript code either if I want to keep Unshield MIT-licensed.

**Comment by twogood** [comment]
TODO: investigate this code: http://unicode.org/resources/utf8.html

**Comment by twogood** [comment]
TODO: Replace the convert_utf with MIT-licensed code
