### ISSUE TITLE
Extracting archive with multiple identical filenames

### ISSUE THREAD

**Issue by laenion** [twogood/unshield#70]
The International Patch for Baldur's Gate 1 (available e.g. from https://www.fileplanet.com/13569/10000/fileinfo/Baldur's-Gate-Patch-%28v.-1.1.4315-International%29) seems to have a strange index: Each group contains the same file in several language specific versions, however the extracted file will always be the Spanish version (probably because it is the last one in the index). This unfortunately makes it impossible to extract the file for a specific language.

Steps to reproduce:
* Unpack the archive
  `7z x bgintl114315.exe`
* View the file _dialog.tlk_ in the package contents
  `unshield l data1 dialog.tlk`
  As can be seen all files appear multiple times.
* Extract the file in any language except Spanish
  `unshield -g "English" x data1 dialog.tlk`
* View the language contents of the file
  `strings ./English/dialog.tlk`

**Comment by twogood** [comment]
Ouch, nice catch!

**Comment by twogood** [comment]
I can reproduce this but I can't find an obvious to solve it without digging deeper into the file format. There are six "file groups":

English
French
German
Italian
Language_Independant
Spanish

But... according to our interpretation of the file format, all of these file groups include all files! So for each file group, it will extract all files, with the Spanish file group last as you noticed.

**Comment by twogood** [comment]
Apparently, I5comp.exe is able to figure it out, so it should be fixable!

```
$ wine64-stable I5comp.exe  g data1.cab 
InstallShield 5.x Cabinet Compression & Maintenance Util
Version 2.01 -] fOSSiL - 1999 [-

VB - Cab volume number where the group begins (1-based)
VE - Cab volume number where the group ends
FF - Index of the first file in the group (0-based)
LF - Index of the last file in the group

 OrigSize  CompSize  VB  VE  FF   LF  Ind Name
========= ========= === === ==== ==== === =====================
  3100553   1166971   1   1  123  123   0 English
  6541406   2481836   1   1  130  131   1 Spanish
  6669860   2517463   1   1  124  125   2 French
  7021662   2682035   1   1  126  127   3 German
  5374492   2251018   1   1    0  122   4 Language Independant
  6504213   2448155   1   1  128  129   5 Italian
```

**Comment by twogood** [comment]
Fixed, please give it a try!

**Comment by laenion** [comment]
Wow, that was fast - thanks a lot, the extraction is working as expected now!

**Comment by twogood** [comment]
My pleasure! PS. If your gratitude is worth a couple of euros, please donate to help treat my friend's 6 year old child who is suffering from the worst kind of brain tumour. Read more at https://www.savinglinnea.com/
