### ISSUE TITLE
 Not extract the data from the data.cab file by unlocking

### ISSUE THREAD

**Issue by goncalveses** [twogood/unshield#72]
I am not able to extract the data.cab file through unshield

data.cab
https://mega.nz/#!Dh0CQLjL!ctzP_Ijd0XfDP6N9bSxpdWP4j7oSuzCJDeKC0mi7Glg

data.hdr
https://mega.nz/#!65Nx3KaD!ctzP_Ijd0XfDP6N9bSxpdWP4j7oSuzCJDeKC0mi7Glg

could you help me extract the files ?

**Comment by twogood** [comment]
I don't have time to look at this right now, but did you try the -O switch "Use old compression"?

**Comment by twogood** [comment]
Never mind about the -O switch. These files do not look like InstallShield files and are not supported by Unshield. Also, the .cab and .hdr files are identical?! I need the whole software package if I should be able to analyze them further. Please reopen this issue if you can provide this.
