### ISSUE TITLE
Prevent CMAKE from the search for a C++ compiler

### ISSUE THREAD

**Issue by maronz** [twogood/unshield#75]
If one wants to have play around with TinyCC one has to stop the search for a C++ compiler.

It seems that this could be achieved with a minimal change in 'CMakeLists.txt' by specifying the language explicitly:
    project(unshield C)
An alternative to changing this line would be to add instead:
    enable_language(C)
Both of these option have been tested successfully.

[ source: https://cmake.org/pipermail/cmake/2010-August/039239.html ]

**Comment by twogood** [comment]
Thank you very much!

**Comment by maronz** [comment]
Well, it's broken again ;)

This time the 
`    project(libunshield)`
entry of 'lib/CMakeLists.txt' would need to be changed to:
`    project(libunshield C)`

As there are two further 'CMakeLists.txt' files (in 'lib/md5' and 'lib/convert_utf') they might as well should receive a similar "treatment" (i.e. adding project entries with explictly stating that the language is to be 'C').

**Comment by twogood** [comment]
Nice catch, thanks!

**Comment by twogood** [comment]
Fixed, thank yuo @maronz
