### ISSUE TITLE
Can't extract InstallShield 17 CAB

### ISSUE THREAD

**Issue by hgdagon** [twogood/unshield#93]
Now, I'm assuming it's InstallShield 17 based on the version of ISSetup.dll. ISCAB just says "Fatal Error", and unshield says a lot of stuff, but I couldn't really figure out how to redirect the output. The problem is all groups get extracted (or so it seems) except for the group/component containing the actual program files.
This is a commercial program of ~7GB total, so I can't upload it. I can, however upload data1.hdr and data1.cab (~20MB), if that will help, however the actual files that fail to extract are in data2.cab.

**Comment by twogood** [comment]
Could be an issue with files >2GB. Maybe you can post the output from unshield here or in a private e-mail to david at activout.se?

**Comment by hgdagon** [comment]
How can I do that? I tried
`unshield ........... >out.txt`

But non of the debug messages were redirected.

**Comment by twogood** [comment]
Append the magic `2>&1` like this:
`unshield ........... >out.txt 2>&1`

Actually it's not magic but it means "forward file descriptor 2 (standard error, stderr) to file descriptor 1 (standard output, stdout)

**Comment by hgdagon** [comment]
Hey, thanks!
Too large for pastebin
https://drive.google.com/open?id=1CK21Aowreutf-fNmy8-uLTOmwxbrJbxi

**Comment by twogood** [comment]
Got it! Could you also provide a list of all data*hdr and data*cab files with exact file sizes?

**Comment by hgdagon** [comment]
Here you go:

data1.hdr 900 KB (921,814 bytes)
data1.cab 21.1 MB (22,130,678 bytes)
data2.cab 6.82 GB (7,332,265,954 bytes)

**Comment by twogood** [comment]
Thanks! I've checked the source code now and support for .cab files > 4GB is simply not there ;)

**Comment by hgdagon** [comment]
OK, so there is no intention to add such support? Provided, I h don't if that wouldtake 2 minutes or 2 years.

Also, posting this here, since this SEEMS to be related. I tried extracting another game, with cab files less than 4GB, and several files in each cab failed to extract, so it seems like the limit is less than 4GB. Unlike the one before, though, I successfully extracted the remaining files with ISCAB.
Here's the info:

data1.hdr 25.3 KB (25,952 bytes)
data1.cab 729 KB (746,638 bytes)
data2.cab 3.41 GB (3,661,981,696 bytes)
data3.cab 3.13 GB (3,366,205,597 bytes)

And here's the [data.hdr and the log](https://github.com/twogood/unshield/files/3444310/Sunrise.zip).

**Comment by twogood** [comment]
I certainly want to fix this!  But I would really need an example, and even then I still can't promise anything.

**Comment by twogood** [comment]
@hgdagon What is the other game? I can probably get hold of Tron Evolution.

**Comment by hgdagon** [comment]
@twogood That's the game! The German version. The Russian one (cabs less than 2GB) extracts fine.

**Comment by twogood** [comment]
Thanks! Switching to Linux won't help, unfortunately.

**Comment by twogood** [comment]
I have Tron Evolution on DVD now, so I should be able to investigate further next week.

**Comment by twogood** [comment]
@hgdagon  Please try the latest unshield build from https://ci.appveyor.com/project/twogood/unshield/build/artifacts

**Comment by hgdagon** [comment]
@twogood Sorry for the silence. I had no internet connection at home for the past month.

I just tried out the latest build, and, sadly, there's not much difference. Nothing changed for both Sunrise discs, and Tron failed to extract data2.cab entirely. No Fatal error this time, the files just `Failed to extract file ...`

**Comment by twogood** [comment]
Ok, please try it on Linux with the latest code from git then.
