### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by thany** [twogood/unshield#97]
Would be nice to pulish binaries as a release asset. I can't compile this on my pc, and I think most people hae the same situation (most people are not application developers).

Since it says the build passes, *something* must have been built ;)
Not sure if that means Linux/macOS/Windows, but those are the ones people likely want.

Shouldn't be too hard to provide these? You gotta build them anyway in order to test if the program still builds at least...

**Comment by twogood** [comment]
*Linux* Should have Unshield in their distro. If the version is too old, file a bug report with the distro.

*Mac OS* Included in Homebrew. If the version is too old, file a bug report with Homebrew.

*Windows* Should be on https://ci.appveyor.com/project/twogood/unshield/build/artifacts but there is an issue with building on AppVeyor that needs fixing

**Comment by thany** [comment]
Maybe it's a good idea to put that information somewhere slightly more prominent?

I for one, couldn't find any clue anywhere that this software is in the distros, on homebrew, or on appveyor.

**Comment by a-detiste** [comment]
Maybe this could help, this is a meta-index of all distro + homebrew: https://repology.org/project/unshield/versions

**Comment by twogood** [comment]
> Maybe it's a good idea to put that information somewhere slightly more prominent?
> 
> I for one, couldn't find any clue anywhere that this software is in the distros, on homebrew, or on appveyor.

Yes, that sounds like a good idea! 

PS. As usual on Open Source projects, pull requests are welcome! ;)

**Comment by twogood** [comment]
> Maybe this could help, this is a meta-index of all distro + homebrew: https://repology.org/project/unshield/versions

Nice, thanks @a-detiste !

**Comment by B-2Admirer** [comment]
Could you explain where I can get the latest Windows binaries? The appveyor link does not seem to contain anything and the repology link does not seem to contain anything for WIndows. Thank you for writing this tool, anyway.
