### ISSUE TITLE
Unable to process old (1997) IS 5.0.2 file set

### ISSUE THREAD

**Issue by phlash** [twogood/unshield#98]
Hi - I'm attempting to unpack / deobfuscate an old InstallShield 5.0.2 file set from 1997 (ZIP available: https://ashbysoft.com/download/dpcb1197-Wireplay.zip). the _sys1.cab and _user1.cab archives unpack using the -O switch, but I have two issues with data1.cab:

1/ the cab doesn't have the data files in - they appear to be already decompressed in the current folder (their file sizes match decompressed size reported by cab listing), unshield errors with 'File <x> is not in the cabinet'.
2/ the data files appear to be obfuscated/encrypted in some way (eg: Readme.txt), I can see unshield has some deobfuscation support but I cannot test it due to issue 1..

FWIW I am one of the original developers of the binaries I'm trying to unpack and happy to have a go at adding out-of-cabinet data file support but wanted to raise the issue here and see if there are any quick checks I can do to discover if the files are obfuscated or encrypted.

**Comment by twogood** [comment]
Hi! Thanks for your message! Have you tried to use the standalone unshield-deobfuscate binary on the files? It is probably not included in any distro but it is part of the project if you build it yourself.

**Comment by phlash** [comment]
Thanks, I built unshield-deobfuscate but sadly it doesn't unmangle any files. I took another look at the file descriptors and they all indicate compressed, not obfuscated (0x0004). Looks like I'll be installing Win95 in a VM and checking this file set does install using setup.exe (16 bit for extra pain when reversing!). wish me luck!

**Comment by phlash** [comment]
Addendum: I hexdumped a few files and despite having decompressed lengths, they all appear to contain END_OF_CHUNK markers, and much lower entropy at the end, will see if opening them separately and decompressing works :)

**Comment by twogood** [comment]
I can probably investigate myself within a couple of days.

**Comment by PhlashGBG** [comment]
Addendum: The original file set does indeed install under Win9x, so I shall continue with out-of-cab file support patch and checking decompressor works despite the files being uncompressed length. I suspect a bug in original IS 5 that writes uncompressed size block after compressing out of cabinet - if so then all out-of-cabinet archives will contain random RAM contents from the machine that generated them :)

**Comment by twogood** [comment]
I debugged it now. It is compressed with the "old" compression method (-O) in the external files, but with the original file sizes exactly as you suspected! I'm half way done with a fix!

**Comment by twogood** [comment]
All .HTM files seem to be missing. 

I get an error extracting WPGAME.EXE that I haven't solved yet.

Do these MD5 sums look correct?

```
596e93bd517f9d9056db083e1a445c63  CLIENT.EXE
b7ef49b0dc87484a7dfd97cb67e47195  GAME.DAT
5184100495b9f83c3fb32767d160524b  LAUNCHER.INI
fe62f30206b08e17d00a6e68c1f42692  MODEM.DAT
c7d807185a6f4bbe10c143dec7156c4b  PSTUB.EXE
74f7bfff760eb090d9e497142b84ccb2  Readme.txt
479e2b6aaea1723043a97f4a7b5a17ec  USERS.INI
886faf562d08664ce941cce3bfb7769e  V20.RES
cb43a12a08b8bd9754483482115ed619  WIRECOMM.EXE
5141cef0ebfa2d204baa01986615c906  WIREDOOM.EXE
664bcc356a9d0068538df71baa45205e  WIREIPX.EXE
2aaa0afb9213c9fccaea0bf7b44d6254  WIREPLAY.BAT
0fff40618a359f26515427b30c9aae8a  WIREPLAY.CFG
eecde17e712b9bf274f70254f49dbcb4  WIREPLAY.INI
34f1efa56118a6220822205f0b5f2080  WIREPLAY.PAL
```

**Comment by twogood** [comment]
Of course the HTM files are in the HELP directory :)

**Comment by phlash** [comment]
Looking good, these are the IS5 extracted file sums:
<pre>
596e93bd517f9d9056db083e1a445c63  CLIENT.EXE
b7ef49b0dc87484a7dfd97cb67e47195  GAME.DAT
5184100495b9f83c3fb32767d160524b  LAUNCHER.INI
fe62f30206b08e17d00a6e68c1f42692  MODEM.DAT
c7d807185a6f4bbe10c143dec7156c4b  PSTUB.EXE
74f7bfff760eb090d9e497142b84ccb2  Readme.txt
2a546de624cdfc74b7b9c62029772b0d  Uninst.isu
479e2b6aaea1723043a97f4a7b5a17ec  USERS.INI
886faf562d08664ce941cce3bfb7769e  V20.RES
cb43a12a08b8bd9754483482115ed619  WIRECOMM.EXE
5141cef0ebfa2d204baa01986615c906  WIREDOOM.EXE
664bcc356a9d0068538df71baa45205e  WIREIPX.EXE
2aaa0afb9213c9fccaea0bf7b44d6254  WIREPLAY.BAT
0fff40618a359f26515427b30c9aae8a  WIREPLAY.CFG
eecde17e712b9bf274f70254f49dbcb4  WIREPLAY.INI
34f1efa56118a6220822205f0b5f2080  WIREPLAY.PAL
db5ea5dd885a508e7273b10c8f60bb86  WPGAME.EXE
</pre>

**Comment by twogood** [comment]
Fixed on master now!
